package pl.edu.agh.soa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-05-18T18:45:48.223+02:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "MainSoapServiceService",
                  wsdlLocation = "http://localhost:8080/soap-api/MainSoapService?wsdl",
                  targetNamespace = "http://soa.agh.edu.pl/")
public class MainSoapServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soa.agh.edu.pl/", "MainSoapServiceService");
    public final static QName MainSoapServicePort = new QName("http://soa.agh.edu.pl/", "MainSoapServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/soap-api/MainSoapService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MainSoapServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/soap-api/MainSoapService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MainSoapServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MainSoapServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MainSoapServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public MainSoapServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MainSoapServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MainSoapServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns MainSoapService
     */
    @WebEndpoint(name = "MainSoapServicePort")
    public MainSoapService getMainSoapServicePort() {
        return super.getPort(MainSoapServicePort, MainSoapService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MainSoapService
     */
    @WebEndpoint(name = "MainSoapServicePort")
    public MainSoapService getMainSoapServicePort(WebServiceFeature... features) {
        return super.getPort(MainSoapServicePort, MainSoapService.class, features);
    }

}
