package pl.edu.agh.soa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-05-18T18:45:48.186+02:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://soa.agh.edu.pl/", name = "MainSoapService")
@XmlSeeAlso({ObjectFactory.class})
public interface MainSoapService {

    @WebMethod
    @RequestWrapper(localName = "downloadAvatar", targetNamespace = "http://soa.agh.edu.pl/", className = "pl.edu.agh.soa.DownloadAvatar")
    @ResponseWrapper(localName = "downloadAvatarResponse", targetNamespace = "http://soa.agh.edu.pl/", className = "pl.edu.agh.soa.DownloadAvatarResponse")
    @WebResult(name = "avatarBase64", targetNamespace = "")
    public java.lang.String downloadAvatar(
        @WebParam(name = "studentId", targetNamespace = "")
        int studentId
    );

    @WebMethod
    @RequestWrapper(localName = "addSubject", targetNamespace = "http://soa.agh.edu.pl/", className = "pl.edu.agh.soa.AddSubject")
    @ResponseWrapper(localName = "addSubjectResponse", targetNamespace = "http://soa.agh.edu.pl/", className = "pl.edu.agh.soa.AddSubjectResponse")
    @WebResult(name = "isOk", targetNamespace = "")
    public java.lang.Boolean addSubject(
        @WebParam(name = "studentId", targetNamespace = "")
        int studentId,
        @WebParam(name = "subject", targetNamespace = "")
        java.lang.String subject
    );

    @WebMethod
    @RequestWrapper(localName = "getStudent", targetNamespace = "http://soa.agh.edu.pl/", className = "pl.edu.agh.soa.GetStudent")
    @ResponseWrapper(localName = "getStudentResponse", targetNamespace = "http://soa.agh.edu.pl/", className = "pl.edu.agh.soa.GetStudentResponse")
    @WebResult(name = "student", targetNamespace = "")
    public pl.edu.agh.soa.Student getStudent(
        @WebParam(name = "studentId", targetNamespace = "")
        int studentId
    );

    @WebMethod
    @RequestWrapper(localName = "addStudent", targetNamespace = "http://soa.agh.edu.pl/", className = "pl.edu.agh.soa.AddStudent")
    @ResponseWrapper(localName = "addStudentResponse", targetNamespace = "http://soa.agh.edu.pl/", className = "pl.edu.agh.soa.AddStudentResponse")
    @WebResult(name = "isOk", targetNamespace = "")
    public java.lang.Boolean addStudent(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "studentId", targetNamespace = "")
        int studentId
    );

    @WebMethod
    @RequestWrapper(localName = "filterBySubject", targetNamespace = "http://soa.agh.edu.pl/", className = "pl.edu.agh.soa.FilterBySubject")
    @ResponseWrapper(localName = "filterBySubjectResponse", targetNamespace = "http://soa.agh.edu.pl/", className = "pl.edu.agh.soa.FilterBySubjectResponse")
    @WebResult(name = "students", targetNamespace = "")
    public java.util.List<pl.edu.agh.soa.Student> filterBySubject(
        @WebParam(name = "subject", targetNamespace = "")
        java.lang.String subject
    );

    @WebMethod
    @RequestWrapper(localName = "filterByName", targetNamespace = "http://soa.agh.edu.pl/", className = "pl.edu.agh.soa.FilterByName")
    @ResponseWrapper(localName = "filterByNameResponse", targetNamespace = "http://soa.agh.edu.pl/", className = "pl.edu.agh.soa.FilterByNameResponse")
    @WebResult(name = "students", targetNamespace = "")
    public java.util.List<pl.edu.agh.soa.Student> filterByName(
        @WebParam(name = "studentName", targetNamespace = "")
        java.lang.String studentName
    );

    @WebMethod
    @RequestWrapper(localName = "removeSubject", targetNamespace = "http://soa.agh.edu.pl/", className = "pl.edu.agh.soa.RemoveSubject")
    @ResponseWrapper(localName = "removeSubjectResponse", targetNamespace = "http://soa.agh.edu.pl/", className = "pl.edu.agh.soa.RemoveSubjectResponse")
    @WebResult(name = "isOk", targetNamespace = "")
    public java.lang.Boolean removeSubject(
        @WebParam(name = "studentId", targetNamespace = "")
        int studentId,
        @WebParam(name = "subject", targetNamespace = "")
        java.lang.String subject
    );

    @WebMethod
    @RequestWrapper(localName = "removeStudent", targetNamespace = "http://soa.agh.edu.pl/", className = "pl.edu.agh.soa.RemoveStudent")
    @ResponseWrapper(localName = "removeStudentResponse", targetNamespace = "http://soa.agh.edu.pl/", className = "pl.edu.agh.soa.RemoveStudentResponse")
    @WebResult(name = "isOk", targetNamespace = "")
    public java.lang.Boolean removeStudent(
        @WebParam(name = "studentId", targetNamespace = "")
        int studentId
    );
}
